/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.poc.movies.inventory;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class InventoryAppTest {

    @Test
    public void appHasAGreeting() {
        InventoryApp classUnderTest = new InventoryApp();
        assertThat(classUnderTest).isNotNull();
    }
}
